version: '3.9'

services:
  app:
    build: .
    container_name: olaclick_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_URL: redis://redis:6379
      CLEANUP_DAYS: ${CLEANUP_DAYS}
      PORT: 3000
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.3
    container_name: olaclick_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: olaclick_redis
    restart: always
    ports:
      - "6379:6379"
